POST http://localhost:5000/api/products/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MjRkNTM1MThkOGZjODc0NTMwNDJiYmMiLCJpYXQiOjE2NDkyMzY0MzR9.ZRItQHSP_w4njbl9eimW3mHVbt6wFFtR4SejEQNY-50

{
    "productName": "AORUS 850W",
    "category": "6247b06c91d48571f2f1dff9",
    "quantity": 5,
    "price": 4990000,
    "properties": "AORUS 850W",
    "image": "/uploads/PSU/psu_aorus_850w_gearvn_large.webp",
    "hot": true
}
###
POST http://localhost:5000/api/orders/new
Content-Type: application/json

{
    "customerName": "Kingston Fury RGB 2x16GB 3600",
    "customerPhone": "6247aee491d48571f2f1dfec",
    "products": [{}],
    "totalPrice": 5390000,
    "customerAddress": "32GB (16GB x 2) / DDR4 / 3600MHz"
}
###
GET http://localhost:5000/api/products/search
Content-Type: application/json

{
    "productName" : "Intel"
}

###
DELETE http://localhost:5000/api/products/624c739a6696a6559716dba9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2MjRkNTM1MThkOGZjODc0NTMwNDJiYmMiLCJpYXQiOjE2NDkyMzY0MzR9.ZRItQHSP_w4njbl9eimW3mHVbt6wFFtR4SejEQNY-50

###
POST http://localhost:5000/api/account/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}
###
POST http://localhost:5000/api/account/register
Content-Type: application/json

{
    "username": "seller",
    "password": "seller"
}
###
GET http://localhost:5000/api/products
Content-Type: application/json

###
GET http://localhost:5000/api/account
Content-Type: application/json

