export const apiUrl = 'http://localhost:5000'

export const LOCAL_STORAGE_CART = 'Gear-shop'

//categories
export const CATE_LOADED_SUCCESS = 'CATE_LOADED_SUCCESS'
export const CATE_LOADED_FAILED = 'CATE_LOADED_FAILED'

//products
export const PRODUCTS_HOT_LOADED_SUCCESS = 'PRODUCTS_HOT_LOADED_SUCCESS'
export const PRODUCTS_HOT_LOADED_FAILED = 'PRODUCTS_HOT_LOADED_FAILED'
export const PRODUCTS_BY_CATEGORY_SUCCESS = 'PRODUCTS_BY_CATEGORY_SUCCESS'
export const PRODUCTS_BY_CATEGORY_FAILED = 'PRODUCTS_BY_CATEGORY_FAILED'
export const PRODUCTS_DETAIL_SUCCESS = 'PRODUCTS_DETAIL_SUCCESS'
export const PRODUCTS_DETAIL_FAILED = 'PRODUCTS_DETAIL_FAILED'