export const apiUrl = 'http://localhost:5000'

export const SET_AUTH = 'SET_AUTH'
export const LOCAL_STORAGE_TOKEN = 'MANAGER TOKEN'

//Product
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS'
export const NEW_PRODUCT_FAILED = 'NEW_PRODUCT_FAILED'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED'

//Order
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED'